### ISSUE TITLE
Doesn't seem to support python 2.7

### ISSUE THREAD

**Issue by prydin** [wavefrontHQ/python-client#20]
I couldn't run the examples with python version <3. Trying it with python 2.7 gave the error message below. Running it with python 3.6.2 works fine. Is this by design? In that case it should be documented!

Error message:
2017-09-11 15:19:30,306 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /api/v2/source
2017-09-11 15:19:30,698 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /api/v2/source
2017-09-11 15:19:31,085 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /api/v2/source
Traceback (most recent call last):
  File "fft.py", line 10, in <module>
    sources = source_api.get_all_source()
  File "/Library/Python/2.7/site-packages/wavefront_api_client/apis/source_api.py", line 384, in get_all_source
    (data) = self.get_all_source_with_http_info(**kwargs)
  File "/Library/Python/2.7/site-packages/wavefront_api_client/apis/source_api.py", line 462, in get_all_source_with_http_info
    collection_formats=collection_formats)
  File "/Library/Python/2.7/site-packages/wavefront_api_client/api_client.py", line 323, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/Library/Python/2.7/site-packages/wavefront_api_client/api_client.py", line 150, in __call_api
    _request_timeout=_request_timeout)
  File "/Library/Python/2.7/site-packages/wavefront_api_client/api_client.py", line 346, in request
    headers=headers)
  File "/Library/Python/2.7/site-packages/wavefront_api_client/rest.py", line 213, in GET
    query_params=query_params)
  File "/Library/Python/2.7/site-packages/wavefront_api_client/rest.py", line 187, in request
    headers=headers)
  File "/Library/Python/2.7/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/Library/Python/2.7/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Library/Python/2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Python/2.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='try.wavefront.com', port=443): Max retries exceeded with url: /api/v2/source (Caused by ProtocolError('Connection aborted.', error(54, 'Connection reset by peer')))

**Comment by basilisk487** [comment]
@prydin This is a OS X-specific issue, that affects all OS X versions - Python 2.7, that ships with the system, is using an outdated version of OpenSSL library, so when it tries to establish a secure connection using TLSv1, which is no longer considered secure, our servers are terminating the connection, and you receive the "Connection reset by peer" error.
To work around this issue, the easiest way would be to install an updated version of Python 2.7 using Homebrew (https://brew.sh). 
Python Software Foundation had a blog post where they explain why is this happening: http://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html

**Comment by prydin** [comment]
Thanks! Closing the issue!
