### ISSUE TITLE
Bug in get_all_dashboard

### ISSUE THREAD

**Issue by mdennehy** [wavefrontHQ/python-client#50]
Hi folks, noticing this in python 3:
```
Exception when calling DashboardAPI: Invalid value for `fixed_legend_filter_field` (), must be one of ['CURRENT', 'MEAN', 'MEDIAN', 'SUM', 'MIN', 'MAX', 'COUNT']
Traceback (most recent call last):
  File "./metricUsage.py", line 93, in <module>
    api_response = dash_api.get_all_dashboard(offset=offset, limit=limit)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api/dashboard_api.py", line 635, in get_all_dashboard
    (data) = self.get_all_dashboard_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api/dashboard_api.py", line 708, in get_all_dashboard_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 169, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 241, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 626, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/models/chart_settings.py", line 228, in __init__
    self.fixed_legend_filter_field = fixed_legend_filter_field
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/models/chart_settings.py", line 491, in fixed_legend_filter_field
    .format(fixed_legend_filter_field, allowed_values)
ValueError: Invalid value for `fixed_legend_filter_field` (), must be one of ['CURRENT', 'MEAN', 'MEDIAN', 'SUM', 'MIN', 'MAX', 'COUNT']
  File "./metricUsage.py", line 114, in <module>
    traceback.print_stack()
```

**Comment by mdennehy** [comment]
Code is just a straight call to DashboardApi.get_all_dashboard:
 ```
   api_response = dash_api.get_all_dashboard(offset=offset, limit=limit)
    if api_response.status.code != 200:
        print("Error calling DashboardAPI: %d %s\n%s\n" % (api_response.code, api_response.message, api_response.result))
        sys.exit(1)

```

**Comment by mdennehy** [comment]
Meanwhile I can query the same REST API call successfully using the requests module:
```
retrivalLimit = 100
url = 'https://workday.wavefront.com/api/v2/dashboard'
header = {'Authorization': 'Bearer ' + wf_api_key}
payload = {'limit': str(retrivalLimit)}

r = requests.get(url, headers=header, params=payload)
dashboardResponse = r.json()
dashboards = dashboardResponse['response']['items']

print(len(dashboards))

retrivedCount = len(dashboardResponse['response']['items'])
while (retrivedCount == retrivalLimit):
    payload = {'limit': str(retrivalLimit),
                'offset': str(len(dashboards))}
    r = requests.get(url, headers=header, params=payload)
    dashboardResponse = r.json()
    dashboards.extend(dashboardResponse['response']['items'])
    retrivedCount = len(dashboardResponse['response']['items'])
    print(len(dashboards))

```

**Comment by mdennehy** [comment]
Can discount this one somewhat folks; we had a dashboard that somehow got created with a null value for fixedLegendFilterField. 

That does of course change this issue from "get_all_dashboard is borked" to "you shouldn't be able to submit bad JSON like that and get a dashboard" combined with "get_all_dashboard should just drop dashboards with bad JSON, not drop every dashboard and fail completely when there's only one that's got an issue". (In my case here, we had one dashboard with bad JSON out of almost 3600 and that caused the entire call to fail).

**Comment by ustinov** [comment]
@mdennehy the client is validating all the fields in response json and is throwing the exception if anything is wrong, you may try catching that exception in your code to find the problematic dashboard.

**Comment by mdennehy** [comment]
It's not just one @ustinov, it's dozens. I patched the one initial one and all was well; then several more showed up. Someone has a script to create them that's doing something odd; they really shouldn't be able to submit illegal JSON and get a dashboard though (they certainly can't for alerts, though there the problem of validation is easier).
