### ISSUE TITLE
Windowing() must be one of ['full', 'last']

### ISSUE THREAD

**Issue by mdennehy** [wavefrontHQ/python-client#59]
Hi folks, 
When making any one of several calls (eg, get_all_dashboards()), I'm seeing an error bubbling up from well down inside the api which seems to be tied to line 1456 in models/chart_settings.py:

`...Exception when calling DashboardAPI: Invalid value for `windowing` (), must be one of ['full', 'last']
Traceback (most recent call last):
  File "./getDashboards.py", line 90, in <module>
    api_response = dash_api.get_all_dashboard(offset=offset, limit=limit)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api/dashboard_api.py", line 635, in get_all_dashboard
    (data) = self.get_all_dashboard_with_http_info(**kwargs)  # noqa: E501
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api/dashboard_api.py", line 708, in get_all_dashboard_with_http_info
    collection_formats=collection_formats)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 169, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 241, in deserialize
    return self.__deserialize(data, response_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in __deserialize
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 258, in <listcomp>
    for sub_data in data]
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/api_client.py", line 626, in __deserialize_model
    instance = klass(**kwargs)
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/models/chart_settings.py", line 305, in __init__
    self.windowing = windowing
  File "/Users/mark.dennehy/.pyenv/versions/wavefront/lib/python3.7/site-packages/wavefront_api_client/models/chart_settings.py", line 1456, in windowing
    .format(windowing, allowed_values)
ValueError: Invalid value for `windowing` (), must be one of ['full', 'last']
  File "./getDashboards.py", line 111, in <module>
    traceback.print_stack()`

I can't prevent that by adding more data to my call of get_all_dashboards():

`   api_response = dash_api.get_all_dashboard(offset=offset, limit=limit)
`

So I think this has to be solved within the client itself.

**Comment by ustinov** [comment]
Thanks for reaching out @mdennehy. Looks like you have charts that were programmatically created or updated without using this API client and as a result have empty `"windowing"` property, which is required to be either `"full"` or `"last"`. I'd suggest finding the malformed dashboard and fixing those.
